
indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: svetlovka
    - url: http://radiomv.ru/
      name: radiomv

server:
  port: 8080

spring:
  datasource:
    username: root
    password: Sngv287h
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
